############################################################
# +------------------------------------------------------+ #
# |               TownyGUI configuration                 | #
# +------------------------------------------------------+ #
############################################################
main_menu: Main
